# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX1)	+= ex1/hello.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX4)	+= ex4/oops.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX5)	+= ex5/api_demo.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX6)	+= ex6/platform_sensor.o
